### ISSUE TITLE
拡張機能の導入方法に沿って導入いたしましたが、main.dart.jsが無いとエラーが出ます

### ISSUE THREAD

**Issue by endo613** [sa8a/chatwork_extension#32]
拡張機能を導入し、表示されたアイコンをクリックしてもアプリが起動しません。
「ポップアップを検証」すると以下のエラーが表示されました。

Failed to load resource: net::ERR_FILE_NOT_FOUND main.dart.js:1

修正するためにはどのようにすればよいでしょうか？

**Comment by sa8a** [comment]
@endo613  様

 #ご連絡いただき、ありがとうございます。

こちらで確認後、修正させていただきますので、お時間いただければ幸いです。
修正後、再度こちらから ご連絡させていただきます🙏

**Comment by endo613** [comment]
@sa8a 様
ありがとうございます。
ぜひよろしくお願いいたします！

**Comment by sa8a** [comment]
@endo613 

endo613 様

以下のリリースにて、先日にいただいていた問題が修正されましたので、ご確認お願いします！
実際に動作確認済みですので、こちらで問題なく使用できるかと思います。

https://github.com/sa8a/chatwork_extension/releases/tag/v1.1.0

大変長らくお待たせしており、申し訳ございませんでした。

**Comment by endo613** [comment]
@sa8a 様
ご対応ありがとうございます！
以下のバージョンにおいて動作を確認することができました！
動作不全の情報提供が不十分であるにもかかわらず、ご対応いただきありがとうございます。

macOS バージョン13.3（22E252）
バージョン: 113.0.5672.126（Official Build） （arm64）

また、上記環境にて動作を確認するにあたり必要な3つのパラメータがあると思いますが、こちらの保存が難しい場面がありましたのでご報告させていただきます。
・バグ？
①一つのパラメータを入れ、他パラメータをコピーするためにソースコード画面へ遷移するとパラメータがリセットされている
②クリップボート拡張アプリにてパラメータをペーストし、保存をしても保存されていない

・解決した方法
②の方法にてパラメータをペーストし、そのままCW画面上にて「一括既読ボタン」を実行する。

以上の方法にて次回移行もパラメータが正しく保存されていることを確認いたしました。
これで私の業務がだいぶ楽になります！本当にありがとうございました！！

**Comment by sa8a** [comment]
@endo613 様

こちらこそ、色々とご確認いただきありがとうございます！

> ①一つのパラメータを入れ、他パラメータをコピーするためにソースコード画面へ遷移するとパラメータがリセットされている

こちらについては、拡張機能を開いたまま別ページに移動すると拡張機能が閉じてしまいます。（拡張機能はそもそもがそういう仕様なので...）
自動保存機能がないため、お手数なのですが、1度保存いただいてから画面の遷移をお願いいたします。

> ②クリップボート拡張アプリにてパラメータをペーストし、保存をしても保存されていない

こちらの動作確認では、問題なく動作していました。。。クリップボードのアプリは「[Clipy](https://clipy.softonic.jp/mac)」というものを使用しています。
また、ユーザービリティーの向上として、以下のリリースで、保存時や一括既読の処理が完了時に、「保存しました！」などというメッセージを表示するように修正していますので、よければ今の拡張機能を削除してから再度新しく入れてみてください。

https://github.com/sa8a/chatwork_extension/releases/tag/v1.2.0

その他、意図しない動作が起きたり、一括既読できないようであれば、一度拡張機能を閉じて再起動するか、再インストールをお願いいたします...

> これで私の業務がだいぶ楽になります！本当にありがとうございました！！

そう言っていただけると、私としても嬉しい限りです....！
また何かありましたら、ご連絡いただければ幸いです。

今後ともよろしくお願いいたします。
